#!/usr/bin/python
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Spark SQL basic example").enableHiveSupport().getOrCreate()

sc = spark.sparkContext
spark.table('hiredata').show()
print(spark.catalog.listTables())
print(spark.conf.get('spark.sql.warehouse.dir'))
